#! /usr/bin/env bash

# Sets a (multi-line) output of the current step.
# Usage: set-output NAME <FILE
name=$1
delim=EOS_${name}_$(openssl rand -hex 16)

echo >>$GITHUB_OUTPUT "$name<<$delim"
cat >>$GITHUB_OUTPUT
echo >>$GITHUB_OUTPUT "$delim"
